# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AngularTour-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ab100670ab224a7a901ea9dc3b008ac6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_949cab18a901490d80e6e1f6f3f9c10a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: ./angular-tour-of-heroes/
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ab100670ab224a7a901ea9dc3b008ac6 }}/jdelacruz087/angular-tour-app:${{ github.sha }}
        file: ./angular-tour-of-heroes/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AngularTour-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6fccf899b3ad4d0cbcec24e473d6ad5d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ab100670ab224a7a901ea9dc3b008ac6 }}/jdelacruz087/angular-tour-app:${{ github.sha }}'
